//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraineData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MigraineDBEntities : DbContext
    {
        public MigraineDBEntities()
            : base("name=MigraineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drink> drink { get; set; }
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<med> med { get; set; }
        public virtual DbSet<migraine> migraine { get; set; }
        public virtual DbSet<migraine_drinks> migraine_drinks { get; set; }
        public virtual DbSet<migraine_foods> migraine_foods { get; set; }
        public virtual DbSet<migraine_location> migraine_location { get; set; }
        public virtual DbSet<migraine_meds> migraine_meds { get; set; }
        public virtual DbSet<migraine_physical_activities> migraine_physical_activities { get; set; }
        public virtual DbSet<painlocation> painlocation { get; set; }
        public virtual DbSet<physicalactivity> physicalactivity { get; set; }
    }
}
