//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigraineData
{
    using System;
    using System.Collections.Generic;
    
    public partial class migraine_physical_activities
    {
        public int id { get; set; }
        public int migraine_id { get; set; }
        public int physicalactivity_id { get; set; }
    
        public virtual migraine migraine { get; set; }
        public virtual physicalactivity physicalactivity { get; set; }
    }
}
